export const contractors = [
  {
    id: 1,
    name: "Apex Plumbing Pros",
    trade: "Plumbing",
    photo: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: false,
    videos: ["/videos/apex1.mp4", "/videos/apex2.mp4"],
    about: "Family-owned plumbing specialists serving the valley for over 15 years. We provide top-quality residential and commercial plumbing services with 24/7 emergency support.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@apexplumbing.com",
  },
  {
    id: 2,
    name: "Elite Electricians",
    trade: "Electrical",
    photo: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: false,
    videos: ["/videos/elite1.mp4"],
    about: "Commercial and residential electrical experts with over 20 years of experience. Specializing in modern electrical installations and smart home solutions.",
    certifications: ["Licensed", "Insured"],
    contact: "info@elitelectric.com",
  },
  {
    id: 3,
    name: "Premier Flooring Solutions",
    trade: "Flooring",
    photo: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: false,
    videos: ["/videos/flooring1.mp4", "/videos/flooring2.mp4"],
    about: "Expert flooring installation and refinishing services. We work with hardwood, tile, carpet, and luxury vinyl with guaranteed craftsmanship.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@premierflooring.com",
  },
  {
    id: 4,
    name: "Solid Concrete Works",
    trade: "Concrete",
    photo: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: true,
    videos: ["/videos/concrete1.mp4"],
    about: "Professional concrete contractors specializing in driveways, patios, foundations, and decorative concrete work.",
    certifications: ["Licensed", "Insured"],
    contact: "info@solidconcrete.com",
  },
  {
    id: 5,
    name: "Rooftop Masters",
    trade: "Roofing",
    photo: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: false,
    videos: ["/videos/roofing1.mp4", "/videos/roofing2.mp4"],
    about: "Complete roofing services including installation, repair, and maintenance. Storm damage specialists with insurance claim assistance.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@rooftopmasters.com",
  },
  {
    id: 6,
    name: "Climate Control HVAC",
    trade: "HVAC",
    photo: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=300&q=80",
    soldOut: false,
    videos: ["/videos/hvac1.mp4"],
    about: "Heating, ventilation, and air conditioning experts. Energy-efficient solutions for residential and commercial properties.",
    certifications: ["Licensed", "Insured"],
    contact: "info@climatecontrolhvac.com",
  },
];

export default contractors;