export const contractors = [
  {
    id: 1,
    name: "Apex Plumbing Pros",
    trade: "Plumbing",
    photo: "/contractors/apex.jpg",
    soldOut: false,
    videos: ["/videos/apex1.mp4", "/videos/apex2.mp4"],
    about: "Family-owned plumbing specialists serving the valley for over 15 years. We provide top-quality residential and commercial plumbing services with 24/7 emergency support.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@apexplumbing.com",
  },
  {
    id: 2,
    name: "Elite Electricians",
    trade: "Electrical",
    photo: "/contractors/elite.jpg",
    soldOut: false,
    videos: ["/videos/elite1.mp4"],
    about: "Commercial and residential electrical experts with over 20 years of experience. Specializing in modern electrical installations and smart home solutions.",
    certifications: ["Licensed", "Insured"],
    contact: "info@elitelectric.com",
  },
  {
    id: 3,
    name: "Premier Flooring Solutions",
    trade: "Flooring",
    photo: "/contractors/flooring.jpg",
    soldOut: false,
    videos: ["/videos/flooring1.mp4", "/videos/flooring2.mp4"],
    about: "Expert flooring installation and refinishing services. We work with hardwood, tile, carpet, and luxury vinyl with guaranteed craftsmanship.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@premierflooring.com",
  },
  {
    id: 4,
    name: "Solid Concrete Works",
    trade: "Concrete",
    photo: "/contractors/concrete.jpg",
    soldOut: true,
    videos: ["/videos/concrete1.mp4"],
    about: "Professional concrete contractors specializing in driveways, patios, foundations, and decorative concrete work.",
    certifications: ["Licensed", "Insured"],
    contact: "info@solidconcrete.com",
  },
  {
    id: 5,
    name: "Rooftop Masters",
    trade: "Roofing",
    photo: "/contractors/roofing.jpg",
    soldOut: false,
    videos: ["/videos/roofing1.mp4", "/videos/roofing2.mp4"],
    about: "Complete roofing services including installation, repair, and maintenance. Storm damage specialists with insurance claim assistance.",
    certifications: ["Licensed", "Bonded", "Insured"],
    contact: "info@rooftopmasters.com",
  },
  {
    id: 6,
    name: "Climate Control HVAC",
    trade: "HVAC",
    photo: "/contractors/hvac.jpg",
    soldOut: false,
    videos: ["/videos/hvac1.mp4"],
    about: "Heating, ventilation, and air conditioning experts. Energy-efficient solutions for residential and commercial properties.",
    certifications: ["Licensed", "Insured"],
    contact: "info@climatecontrolhvac.com",
  },
];

export default contractors;